export const Actions = {
    PAGE_SIGN: 'PAGE_SIGN',
    PAGE_MAIN: 'PAGE_MAIN',

    CREATE_CONVERSATION: 'CREATE_CONVERSATION',
    LOAD_CONVERSATION_LIST: 'LOAD_CONVERSATION_LIST',
    SAVE_CONVERSATION_LIST: 'SAVE_CONVERSATION_LIST',

    CHANGE_CONVERSATION: 'CHANGE_CONVERSATION',

    CHAT_MESSAGE: 'CHAT_MESSAGE',
    SAVE_MESSAGE: 'SAVE_MESSAGE',

    SAVE_USER_DATA: 'SAVE_USER_DATA',
    SAVE_ALL_USER: 'SAVE_ALL_USER',
    SAVE_LIST_USER: 'SAVE_LIST_USER',
    SAVE_STATUS: ' SAVE_STATUS',

    SAVE_STATUS_FRIEND: ' SAVE_STATUS_FRIEND',
    ADD_MEMBER: 'ADD_MEMBER',
    ADD_MEMBER_GROUP_CONVERSATION: 'ADD_MEMBER_GROUP_CONVERSATION',
    ADD_MEMBER_GROUP_USER: 'ADD_MEMBER_GROUP_USER',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SIGNUP: 'SIGNUP',
    CONNECT: 'CONNECT',
    DISCONNECT: 'DISCONNECT',
    SAVE_USER_ONLINE: 'SAVE_USER_ONLINE',
    SAVE_NEW_ONLINE: 'SAVE_NEW_ONLINE',

    LOGOUT_USER_DATA: 'LOGOUT_USER_DATA',
    LOGOUT_CONSELECTED: 'LOGOUT_CONSELECTED',
    LOGOUT_CONVERSATION: 'LOGOUT_CONVERSATION',
    LOGOUT_LIST_USER: 'LOGOUT_LIST_USER',
    LOGOUT_MESSAGE: 'LOGOUT_MESSAGE',
    LOGOUT_STATUS_FRIEND: 'LOGOUT_STATUS_FRIEND',
    LOGOUT_USER: 'LOGOUT_USER',
};